apiVersion: tap.terasky.com/v1alpha1
kind: SQLServerInstance
metadata:
  name: guy-01
  namespace: demo
spec:
  storageGB: 20
  test:
    sub1: f
    subObj:
      intField: 4
      strField: f
  compositeDeletePolicy: Foreground
  writeConnectionSecretToRef:
    name: demo-01-secret
  compositionUpdatePolicy: Automatic
  compositionRef:
    name: xsqlserverinstances.tap.terasky.com
