apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: yelb-appserver
  namespace: default
  annotations:
    backstage.io/source-location: url:https://github.com/dambor/yelb-catalog
    backstage.io/techdocs-ref: >-
      url:https://github.com/dambor/yelb-catalog/blob/main/components/yelb-appserver
    backstage.io/kubernetes-label-selector: app=yelb-appserver,tier=middletier
spec:
  type: service
  system: yelb
  owner: dev-team
  lifecycle: experimental
  dependsOn:
    - Component:yelb-db
    - Component:yelb-redis
