apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test
  title: Create a new test
  description: Create a new test
spec:
  owner: group:default/engineering
  type: service
  parameters:
    - title: spec
      properties:
        spec:
          type: object
          properties:
            name:
              description: the cluster name to create
              type: string
            size:
              default: small
              description: the size of the cluster
              enum:
              - small
              - medium
              - large
              type: string
          type: object
      type: object
    - title: Repository to place document
      properties:
        repoUrl:
          content:
            type: string
          description: Name of repository
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: Creating ${{ parameters.spec.name }}/resource.yaml
    - id: serialize
      name: Serialize
      action: roadiehq:utils:serialize:json
      input:
        data: ${{ parameters.spec }}
    - id: generate-yaml
      action: roadiehq:utils:fs:write
      input:
        path: resource.yaml
        content: >
          apiVersion: test.terasky.com/v1alpha1
          kind: Database
          metadata:
            name: ${{ parameters.spec.name }}
          spec: ${{ steps['serialize'].output.serialized }}
    - id: create-pull-request
      name: create-pull-request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: create-${{ parameters.spec.name }}-resource
        title: DB - ${{ parameters.spec.name }}
        description: Creat Resource for ${{ parameters.spec.size }}
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: random-example
  title: random-example
  description: random-example
spec:
  owner: group:default/tkg-admins
  type: service
  parameters:
    - title: spec
      properties:
        name:
          description: the cluster name to create
          type: string
        size:
          default: small
          description: the size of the cluster
          enum:
          - small
          - medium
          - large
          type: string
      type: object
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: example template
    - action: fetch:plain:file
      id: fetch-plain-file
      name: Fetch plain file
      input:
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions/assets/Backstage%20Community%20Sessions.png
        targetPath: target-path
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: random-example-to-fail
  title: random-example-to-fail
  description: random-example
spec:
  owner: group:default/tkg-admins
  type: service
  parameters:
    - title: spec
      properties:
        name:
          description: the cluster name to create
          type: string
        size:
          default: small
          description: the size of the cluster
          enum:
          - small
          - medium
          - large
          type: string
      type: object
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: example template
    - action: fetch:plain:file
      id: fetch-plain-file-fail
      name: Fetch plain file - fail
      input:
        url: https://github.com/backstage/communasdasdfity/tree/main/backstage-community-sessions/assets/Backstage%20Community%20Sessions.png
        targetPath: target-path
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: logging-example
  title: logging-example
  description: logging-example
spec:
  owner: group:default/tkg-admins
  type: service
  parameters:
    - title: spec
      properties:
        claimRef:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            name:
              type: string
            namespace:
              type: string
          required:
          - apiVersion
          - kind
          - namespace
          - name
          type: object
        compositionRef:
          properties:
            name:
              type: string
          required:
          - name
          type: object
        compositionRevisionRef:
          properties:
            name:
              type: string
          required:
          - name
          type: object
        compositionRevisionSelector:
          properties:
            matchLabels:
              additionalProperties:
                type: string
              type: object
          required:
          - matchLabels
          type: object
        compositionSelector:
          properties:
            matchLabels:
              additionalProperties:
                type: string
              type: object
          required:
          - matchLabels
          type: object
        compositionUpdatePolicy:
          enum:
          - Automatic
          - Manual
          type: string
        environmentConfigRefs:
          items:
            properties:
              apiVersion:
                type: string
              kind:
                type: string
              name:
                type: string
            required:
            - apiVersion
            - kind
            type: object
          type: array
        name:
          description: the cluster name to create
          type: string
        publishConnectionDetailsTo:
          properties:
            configRef:
              default:
                name: default
              properties:
                name:
                  type: string
              type: object
            metadata:
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                labels:
                  additionalProperties:
                    type: string
                  type: object
                type:
                  type: string
              type: object
            name:
              type: string
          required:
          - name
          type: object
        resourceRefs:
          items:
            properties:
              apiVersion:
                type: string
              kind:
                type: string
              name:
                type: string
            required:
            - apiVersion
            - kind
            type: object
          type: array
          x-kubernetes-list-type: atomic
        size:
          default: small
          description: the size of the cluster
          enum:
          - small
          - medium
          - large
          type: string
        writeConnectionSecretToRef:
          properties:
            name:
              type: string
            namespace:
              type: string
          required:
          - name
          - namespace
          type: object
      type: object

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: example template
