apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels: 
        kubevirt.io/size: 2xlarge
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootfs
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 24Gi
      networks:
      - name: private-network-01
        pod: {}
      volumes:
        - name: rootfs
          containerDisk:
            image: harbor.terasky.demo/templates/ubuntu:22.04
        - name: cloudinit
          cloudInitNoCloud:
            userDataBase64: SGkuXG4= 
